// MESS ORACLE — Full Menu Data (atomic items, mix-and-match ready)
// Each item is a single dish/component. No compound + entries.

const FOOD_GLOSSARY = {
  "kuzhambu": "thick tamarind-based curry, usually spicy",
  "kara kuzhambu": "spicy tamarind curry with veggies or lentils",
  "vathakuzhambu": "tangy sun-dried berry tamarind curry — very spicy",
  "milagu rasam": "thin black pepper soup, great for digestion",
  "pineapple rasam": "sweet-tangy thin soup with pineapple",
  "mysore rasam": "aromatic rasam with coconut and spices",
  "tomato rasam": "light, tangy tomato-based soup",
  "moong dal rasam": "thin lentil-based soup with moong",
  "paruppu rasam": "thin lentil soup, everyday comfort",
  "arachuvitta sambar": "freshly ground coconut sambar — richer than normal",
  "poriyal": "dry stir-fried vegetable side dish",
  "keerai porial": "stir-fried leafy greens (spinach/amaranth)",
  "raw banana poriyal": "stir-fried raw plantain, mildly spiced",
  "broad beans poriyal": "stir-fried broad beans with coconut",
  "mixed vegetable porial": "assorted veggie stir-fry",
  "paruppu podi": "spiced lentil powder — mix with ghee and rice",
  "thovayal": "thick chutney made from roasted lentils/coconut",
  "thuvaiyal": "thick chutney-style condiment",
  "podi oil": "spiced lentil powder with gingelly oil",
  "gingelly oil": "sesame oil — nutty, traditional Tamil flavour",
  "fryams": "fried papad strips — crunchy, empty calories",
  "udap": "urad dal based condiment",
  "bisibelabath": "Karnataka one-pot rice+dal+veggie dish, spiced",
  "vadacurry": "spiced lentil patty curry, goes great with idli",
  "rawa khichdi": "semolina porridge, savoury breakfast",
  "semiya khidi": "vermicelli upma — thin noodle breakfast porridge",
  "andhra noonn": "Andhra-style naan, usually very spicy",
  "chettinad": "fiery spice blend from Chettinad region — heavy pepper",
  "kadhi pakoda": "yoghurt-based gravy with fried fritters",
  "millet buttermilk": "buttermilk with millet flour — probiotic, filling",
  "badam milk": "almond milk sweetened with saffron/cardamom",
  "poha": "flattened rice, light breakfast staple",
  "bhajiya": "deep-fried snack fritters",
  "idli": "steamed rice-lentil cakes — ~70 kcal each, very clean",
  "phulka": "thin unleavened wheat flatbread, lighter than chapati",
  "jeera dal": "cumin-tempered lentil soup",
  "chenna masala": "white chickpea curry",
  "white chana masala": "spiced white chickpea curry",
  "rasam": "thin spiced soup — digestive, low calorie",
  "sambar": "lentil and vegetable stew — the backbone of South Indian meals",
  "pongal": "soft rice-lentil porridge, comforting and mild",
  "buttermilk": "diluted curd with spices — excellent probiotic",
  "raita": "yoghurt with vegetables — cooling side",
};

const MENU = {
  monday: {
    breakfast: [
      { name: "Vegetable Vermicelli Upma",   serving: "1 plate (~200g)",      tags: ["veg","light"],          protein: 6,  carbs: 35, fat: 5,  cal: 210 },
      { name: "Coconut Chutney",              serving: "2 tbsp",               tags: ["veg","light"],          protein: 1,  carbs: 4,  fat: 4,  cal: 55  },
      { name: "Pongal",                       serving: "1 bowl (~200g)",       tags: ["veg","rice"],           protein: 5,  carbs: 32, fat: 4,  cal: 185 },
      { name: "Sambar",                       serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 4,  carbs: 10, fat: 1,  cal: 65  },
      { name: "Toasted Bread",                serving: "2 slices",             tags: ["veg","bread"],          protein: 4,  carbs: 26, fat: 2,  cal: 140 },
      { name: "Butter",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 4,  cal: 36  },
      { name: "Jam",                          serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 6,  fat: 0,  cal: 25  },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
      { name: "Boiled Egg",                   serving: "1 egg",                tags: ["nonveg","protein"],     protein: 6,  carbs: 0,  fat: 5,  cal: 70  },
    ],
    lunch: [
      { name: "Chapati",                      serving: "2 rotis",              tags: ["veg","bread"],          protein: 6,  carbs: 30, fat: 2,  cal: 162 },
      { name: "Dal Fry",                      serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 9,  carbs: 20, fat: 3,  cal: 143 },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Kara Kuzhambu",                serving: "1 ladle (100ml)",      tags: ["veg","rice"],           protein: 2,  carbs: 10, fat: 2,  cal: 66  },
      { name: "Carrot & Beans Poriyal",       serving: "1 katori (~80g)",      tags: ["veg","light"],          protein: 2,  carbs: 10, fat: 2,  cal: 65  },
      { name: "Paruppu Rasam",                serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 3,  carbs: 8,  fat: 1,  cal: 55  },
      { name: "Paruppu Podi",                 serving: "1 tsp",                tags: ["veg","light"],          protein: 2,  carbs: 4,  fat: 1,  cal: 33  },
      { name: "Gingelly Oil",                 serving: "½ tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 2,  cal: 18  },
      { name: "Thuvaiyal Pickle",             serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 2,  fat: 0,  cal: 10  },
      { name: "Fryums",                       serving: "5–6 pieces",           tags: ["veg","light"],          protein: 1,  carbs: 6,  fat: 2,  cal: 45  },
      { name: "Watermelon",                   serving: "1 slice (~150g)",      tags: ["veg","light"],          protein: 1,  carbs: 11, fat: 0,  cal: 46  },
      { name: "Curd",                         serving: "1 katori (100g)",      tags: ["veg","protein"],        protein: 3,  carbs: 4,  fat: 2,  cal: 46  },
      { name: "Lemon Mint Juice",             serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 0,  carbs: 8,  fat: 0,  cal: 32  },
    ],
    snacks: [
      { name: "Paneer Sandwich",              serving: "1 sandwich (2 slices)",tags: ["veg","bread","protein"],protein: 14, carbs: 28, fat: 10, cal: 255 },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
    ],
    dinner: [
      { name: "Phulka",                       serving: "3 phulkas",            tags: ["veg","bread"],          protein: 6,  carbs: 30, fat: 2,  cal: 162 },
      { name: "White Chenna Masala",          serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 9,  carbs: 18, fat: 3,  cal: 135 },
      { name: "Jeera Dal",                    serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 7,  carbs: 16, fat: 2,  cal: 110 },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Dry Cabbage Porial",           serving: "1 katori (~80g)",      tags: ["veg","light"],          protein: 2,  carbs: 8,  fat: 1,  cal: 50  },
      { name: "Rasam",                        serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 1,  carbs: 5,  fat: 0,  cal: 25  },
      { name: "Pickle",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 1,  fat: 0,  cal: 5   },
      { name: "Ice Cream",                    serving: "1 small scoop (~60g)", tags: ["veg","light"],          protein: 2,  carbs: 14, fat: 4,  cal: 100 },
      { name: "Salad (Cucumber + Carrot)",    serving: "1 katori (~100g)",     tags: ["veg","light"],          protein: 1,  carbs: 6,  fat: 0,  cal: 28  },
      { name: "Milk",                         serving: "1 glass (200ml)",      tags: ["veg","protein"],        protein: 6,  carbs: 10, fat: 4,  cal: 100 },
      { name: "Curd",                         serving: "1 katori (100g)",      tags: ["veg","protein"],        protein: 3,  carbs: 4,  fat: 2,  cal: 46  },
    ],
  },

  tuesday: {
    breakfast: [
      { name: "Idli",                         serving: "3 idlis",              tags: ["veg","light"],          protein: 5,  carbs: 30, fat: 1,  cal: 150 },
      { name: "Sambar",                       serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 4,  carbs: 10, fat: 1,  cal: 65  },
      { name: "Mint Chutney",                 serving: "2 tbsp",               tags: ["veg","light"],          protein: 1,  carbs: 2,  fat: 1,  cal: 21  },
      { name: "Podi Oil",                     serving: "1 tsp podi + ½ tsp oil",tags:["veg","light"],         protein: 2,  carbs: 3,  fat: 3,  cal: 47  },
      { name: "Poha",                         serving: "½ cup (~80g)",         tags: ["veg","light"],          protein: 2,  carbs: 16, fat: 2,  cal: 90  },
      { name: "Bhajiya",                      serving: "2 pieces",             tags: ["veg","light"],          protein: 2,  carbs: 8,  fat: 4,  cal: 75  },
      { name: "Chopped Onion + Lemon",        serving: "2 tbsp",               tags: ["veg","light"],          protein: 0,  carbs: 3,  fat: 0,  cal: 15  },
      { name: "Wheat Bread",                  serving: "2 slices",             tags: ["veg","bread"],          protein: 4,  carbs: 26, fat: 2,  cal: 140 },
      { name: "Butter",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 4,  cal: 36  },
      { name: "Jam",                          serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 6,  fat: 0,  cal: 25  },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
      { name: "Egg Bhurji",                   serving: "2 eggs scrambled",     tags: ["nonveg","protein"],     protein: 10, carbs: 2,  fat: 8,  cal: 120 },
    ],
    lunch: [
      { name: "Veg Biryani",                  serving: "1 plate (~300g)",      tags: ["veg","rice"],           protein: 7,  carbs: 55, fat: 7,  cal: 310 },
      { name: "Onion Raita",                  serving: "1 katori (100g)",      tags: ["veg","protein"],        protein: 3,  carbs: 5,  fat: 1,  cal: 42  },
      { name: "Methi Dal",                    serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 7,  carbs: 14, fat: 2,  cal: 106 },
      { name: "Mixed Vegetable Kadhi",        serving: "1 katori (~150g)",     tags: ["veg","light"],          protein: 3,  carbs: 8,  fat: 2,  cal: 62  },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Sambar",                       serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 4,  carbs: 10, fat: 1,  cal: 65  },
      { name: "Udap",                         serving: "1 tsp",                tags: ["veg","light"],          protein: 1,  carbs: 2,  fat: 0,  cal: 12  },
      { name: "Tomato Rasam",                 serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 1,  carbs: 5,  fat: 0,  cal: 25  },
      { name: "Curd",                         serving: "1 katori (100g)",      tags: ["veg","protein"],        protein: 3,  carbs: 4,  fat: 2,  cal: 46  },
      { name: "Paruppu Podi",                 serving: "1 tsp",                tags: ["veg","light"],          protein: 2,  carbs: 4,  fat: 1,  cal: 33  },
      { name: "Ghee",                         serving: "½ tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 2,  cal: 18  },
      { name: "Thovayal",                     serving: "1 tsp",                tags: ["veg","light"],          protein: 1,  carbs: 2,  fat: 1,  cal: 21  },
      { name: "Pickle",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 1,  fat: 0,  cal: 5   },
      { name: "Papad",                        serving: "1 papad",              tags: ["veg","light"],          protein: 2,  carbs: 7,  fat: 1,  cal: 45  },
      { name: "Lemon Mint Juice",             serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 0,  carbs: 8,  fat: 0,  cal: 32  },
    ],
    snacks: [
      { name: "Masala Peanut",                serving: "1 small cup (~50g)",   tags: ["veg","protein"],        protein: 7,  carbs: 10, fat: 7,  cal: 135 },
      { name: "Veg Puff (even weeks)",        serving: "1 puff",               tags: ["veg","light"],          protein: 3,  carbs: 18, fat: 6,  cal: 138 },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
    ],
    dinner: [
      { name: "Masala Dosa",                  serving: "1 dosa",               tags: ["veg","light"],          protein: 4,  carbs: 36, fat: 5,  cal: 205 },
      { name: "Coconut Chutney",              serving: "2 tbsp",               tags: ["veg","light"],          protein: 1,  carbs: 4,  fat: 4,  cal: 55  },
      { name: "Sambar",                       serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 4,  carbs: 10, fat: 1,  cal: 65  },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Rasam",                        serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 1,  carbs: 5,  fat: 0,  cal: 25  },
      { name: "Pickle",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 1,  fat: 0,  cal: 5   },
      { name: "Milk",                         serving: "1 glass (250ml)",      tags: ["veg","protein"],        protein: 8,  carbs: 12, fat: 5,  cal: 125 },
      { name: "Salad (Cucumber + Carrot)",    serving: "1 katori (~100g)",     tags: ["veg","light"],          protein: 1,  carbs: 6,  fat: 0,  cal: 28  },
      { name: "Buttermilk",                   serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 3,  carbs: 4,  fat: 2,  cal: 45  },
    ],
  },

  wednesday: {
    breakfast: [
      { name: "Puri",                         serving: "3 puris",              tags: ["veg","bread"],          protein: 4,  carbs: 30, fat: 9,  cal: 219 },
      { name: "Aloo Masala",                  serving: "1 katori (~120g)",     tags: ["veg","light"],          protein: 3,  carbs: 18, fat: 3,  cal: 111 },
      { name: "Rawa Khichdi",                 serving: "1 plate (~200g)",      tags: ["veg","light"],          protein: 5,  carbs: 35, fat: 4,  cal: 196 },
      { name: "Coconut Chutney",              serving: "2 tbsp",               tags: ["veg","light"],          protein: 1,  carbs: 4,  fat: 4,  cal: 55  },
      { name: "Bread",                        serving: "2 slices",             tags: ["veg","bread"],          protein: 4,  carbs: 26, fat: 2,  cal: 140 },
      { name: "Butter",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 4,  cal: 36  },
      { name: "Jam",                          serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 6,  fat: 0,  cal: 25  },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
      { name: "Boiled Egg",                   serving: "1 egg",                tags: ["nonveg","protein"],     protein: 6,  carbs: 0,  fat: 5,  cal: 70  },
    ],
    lunch: [
      { name: "Palak Paneer",                 serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 12, carbs: 10, fat: 10, cal: 175, exclusiveGroup: "wed-lunch-main" },
      { name: "Chicken Handi Masala",         serving: "1 katori (~150g)",     tags: ["nonveg","protein"],     protein: 22, carbs: 8,  fat: 12, cal: 225, exclusiveGroup: "wed-lunch-main" },
      { name: "Chapati",                      serving: "2 rotis",              tags: ["veg","bread"],          protein: 6,  carbs: 30, fat: 2,  cal: 162 },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Arachuvitta Sambar",           serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 4,  carbs: 12, fat: 2,  cal: 82  },
      { name: "Broad Beans Poriyal",          serving: "1 katori (~80g)",      tags: ["veg","light"],          protein: 3,  carbs: 10, fat: 2,  cal: 70  },
      { name: "Milagu Rasam",                 serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 1,  carbs: 5,  fat: 1,  cal: 33  },
      { name: "Paruppu Podi",                 serving: "1 tsp",                tags: ["veg","light"],          protein: 2,  carbs: 4,  fat: 1,  cal: 33  },
      { name: "Ghee",                         serving: "½ tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 2,  cal: 18  },
      { name: "Thovayal",                     serving: "1 tsp",                tags: ["veg","light"],          protein: 1,  carbs: 2,  fat: 1,  cal: 21  },
      { name: "Pickle",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 1,  fat: 0,  cal: 5   },
      { name: "Mixed Fruit",                  serving: "1 cup (~150g)",        tags: ["veg","light"],          protein: 1,  carbs: 18, fat: 0,  cal: 72  },
      { name: "Buttermilk",                   serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 3,  carbs: 4,  fat: 2,  cal: 45  },
      { name: "Lemon Mint Juice",             serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 0,  carbs: 8,  fat: 0,  cal: 32  },
    ],
    snacks: [
      { name: "Pasta (red/white sauce)",      serving: "1 bowl (~200g)",       tags: ["veg","light"],          protein: 6,  carbs: 32, fat: 5,  cal: 200 },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
    ],
    dinner: [
      { name: "White Chana Masala",           serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 10, carbs: 20, fat: 4,  cal: 156 },
      { name: "Vegetable Biryani",            serving: "1 plate (~300g)",      tags: ["veg","rice"],           protein: 7,  carbs: 55, fat: 5,  cal: 293 },
      { name: "Idli",                         serving: "3 idlis",              tags: ["veg","light"],          protein: 5,  carbs: 30, fat: 1,  cal: 150 },
      { name: "Sambar",                       serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 4,  carbs: 10, fat: 1,  cal: 65  },
      { name: "Coconut Chutney",              serving: "2 tbsp",               tags: ["veg","light"],          protein: 1,  carbs: 4,  fat: 4,  cal: 55  },
      { name: "Chettinaadu Egg Masala",       serving: "2 eggs in gravy",      tags: ["nonveg","protein"],     protein: 12, carbs: 8,  fat: 10, cal: 170 },
      { name: "Rasam",                        serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 1,  carbs: 5,  fat: 0,  cal: 25  },
      { name: "Curd",                         serving: "1 katori (100g)",      tags: ["veg","protein"],        protein: 3,  carbs: 4,  fat: 2,  cal: 46  },
      { name: "Salad (Beetroot + Carrot + Cucumber)", serving: "1 katori (~100g)", tags: ["veg","light"],     protein: 1,  carbs: 10, fat: 0,  cal: 44  },
      { name: "Strawberry Milk",              serving: "1 glass (200ml)",      tags: ["veg","protein"],        protein: 5,  carbs: 16, fat: 3,  cal: 111 },
    ],
  },

  thursday: {
    breakfast: [
      { name: "Idli",                         serving: "3 idlis",              tags: ["veg","light"],          protein: 5,  carbs: 30, fat: 1,  cal: 150 },
      { name: "Vadacurry",                    serving: "1 katori (~120g)",     tags: ["veg","light"],          protein: 5,  carbs: 16, fat: 4,  cal: 120 },
      { name: "Ground Nut Chutney",           serving: "2 tbsp",               tags: ["veg","protein"],        protein: 3,  carbs: 3,  fat: 5,  cal: 69  },
      { name: "Pav",                          serving: "2 buns",               tags: ["veg","bread"],          protein: 5,  carbs: 30, fat: 2,  cal: 162 },
      { name: "Bhaji",                        serving: "1 katori (~120g)",     tags: ["veg","light"],          protein: 3,  carbs: 16, fat: 4,  cal: 112 },
      { name: "Chopped Onion",                serving: "2 tbsp",               tags: ["veg","light"],          protein: 0,  carbs: 2,  fat: 0,  cal: 8   },
      { name: "Bread",                        serving: "2 slices",             tags: ["veg","bread"],          protein: 4,  carbs: 26, fat: 2,  cal: 140 },
      { name: "Butter",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 4,  cal: 36  },
      { name: "Jam",                          serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 6,  fat: 0,  cal: 25  },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
      { name: "Boiled Egg",                   serving: "1 egg",                tags: ["nonveg","protein"],     protein: 6,  carbs: 0,  fat: 5,  cal: 70  },
    ],
    lunch: [
      { name: "Bisibelabath",                 serving: "1 plate (~300g)",      tags: ["veg","rice"],           protein: 8,  carbs: 55, fat: 6,  cal: 310 },
      { name: "Potato Chips",                 serving: "small handful (~30g)", tags: ["veg","light"],          protein: 2,  carbs: 16, fat: 5,  cal: 117 },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Dal Fry",                      serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 9,  carbs: 20, fat: 3,  cal: 143 },
      { name: "Raw Banana Poriyal",           serving: "1 katori (~80g)",      tags: ["veg","light"],          protein: 2,  carbs: 14, fat: 2,  cal: 82  },
      { name: "Pineapple Rasam",              serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 1,  carbs: 8,  fat: 0,  cal: 36  },
      { name: "Curd",                         serving: "1 katori (100g)",      tags: ["veg","protein"],        protein: 3,  carbs: 4,  fat: 2,  cal: 46  },
      { name: "Paruppu Podi",                 serving: "1 tsp",                tags: ["veg","light"],          protein: 2,  carbs: 4,  fat: 1,  cal: 33  },
      { name: "Gingelly Oil",                 serving: "½ tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 2,  cal: 18  },
      { name: "Thovayal",                     serving: "1 tsp",                tags: ["veg","light"],          protein: 1,  carbs: 2,  fat: 1,  cal: 21  },
      { name: "Pickle",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 1,  fat: 0,  cal: 5   },
      { name: "Fruit Salad (Black Grapes + Pineapple)", serving: "1 katori (~150g)", tags: ["veg","light"],   protein: 1,  carbs: 18, fat: 0,  cal: 75  },
      { name: "Lemon Mint Juice",             serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 0,  carbs: 8,  fat: 0,  cal: 32  },
    ],
    snacks: [
      { name: "Masala Sweet Corn",            serving: "1 cup (~100g)",        tags: ["veg","light"],          protein: 4,  carbs: 22, fat: 2,  cal: 120 },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
    ],
    dinner: [
      { name: "Soya Chunk Gravy",             serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 14, carbs: 15, fat: 4,  cal: 152 },
      { name: "Phulka",                       serving: "3 phulkas",            tags: ["veg","bread"],          protein: 6,  carbs: 30, fat: 2,  cal: 162 },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Dal Fry",                      serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 9,  carbs: 20, fat: 3,  cal: 143 },
      { name: "Sambar",                       serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 4,  carbs: 10, fat: 1,  cal: 65  },
      { name: "Mixed Vegetable Porial",       serving: "1 katori (~100g)",     tags: ["veg","light"],          protein: 2,  carbs: 10, fat: 2,  cal: 66  },
      { name: "Rasam",                        serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 1,  carbs: 5,  fat: 0,  cal: 25  },
      { name: "Pickle",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 1,  fat: 0,  cal: 5   },
      { name: "Salad (Cucumber + Carrot)",    serving: "1 katori (~100g)",     tags: ["veg","light"],          protein: 1,  carbs: 6,  fat: 0,  cal: 28  },
      { name: "Milk",                         serving: "1 glass (250ml)",      tags: ["veg","protein"],        protein: 8,  carbs: 12, fat: 5,  cal: 125 },
      { name: "Buttermilk",                   serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 3,  carbs: 4,  fat: 2,  cal: 45  },
      { name: "Cold Badam Milk (veg only)",   serving: "1 glass (200ml)",      tags: ["veg","protein"],        protein: 5,  carbs: 18, fat: 4,  cal: 130 },
    ],
  },

  friday: {
    breakfast: [
      { name: "Dosa",                         serving: "1 dosa",               tags: ["veg","light"],          protein: 3,  carbs: 28, fat: 3,  cal: 151 },
      { name: "Sambar",                       serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 4,  carbs: 10, fat: 1,  cal: 65  },
      { name: "Tomato Chutney",               serving: "2 tbsp",               tags: ["veg","light"],          protein: 1,  carbs: 3,  fat: 1,  cal: 25  },
      { name: "Semiya Khidi",                 serving: "1 plate (~200g)",      tags: ["veg","light"],          protein: 5,  carbs: 38, fat: 4,  cal: 210 },
      { name: "Podi Oil",                     serving: "1 tsp podi + ½ tsp oil",tags:["veg","light"],         protein: 2,  carbs: 3,  fat: 3,  cal: 47  },
      { name: "Wheat Bread",                  serving: "2 slices",             tags: ["veg","bread"],          protein: 4,  carbs: 26, fat: 2,  cal: 140 },
      { name: "Butter",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 4,  cal: 36  },
      { name: "Jam",                          serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 6,  fat: 0,  cal: 25  },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
      { name: "Egg Bhurji",                   serving: "2 eggs scrambled",     tags: ["nonveg","protein"],     protein: 10, carbs: 2,  fat: 8,  cal: 120 },
    ],
    lunch: [
      { name: "Chapati",                      serving: "2 rotis",              tags: ["veg","bread"],          protein: 6,  carbs: 30, fat: 2,  cal: 162 },
      { name: "Paneer Tikka Masala",          serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 14, carbs: 10, fat: 10, cal: 186, exclusiveGroup: "fri-lunch-main" },
      { name: "Chicken Chettinad Masala",     serving: "1 katori (~150g)",     tags: ["nonveg","protein"],     protein: 22, carbs: 6,  fat: 12, cal: 216, exclusiveGroup: "fri-lunch-main" },
      { name: "Andhra Noonn",                 serving: "1 naan",               tags: ["nonveg","bread"],       protein: 4,  carbs: 28, fat: 3,  cal: 155 },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Potato Bhindi Dry",            serving: "1 katori (~80g)",      tags: ["veg","light"],          protein: 2,  carbs: 12, fat: 3,  cal: 83  },
      { name: "Moong Dal Rasam",              serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 0,  cal: 32  },
      { name: "Sweet Buttermilk",             serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 3,  carbs: 6,  fat: 2,  cal: 54  },
      { name: "Paruppu Podi",                 serving: "1 tsp",                tags: ["veg","light"],          protein: 2,  carbs: 4,  fat: 1,  cal: 33  },
      { name: "Ghee",                         serving: "½ tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 2,  cal: 18  },
      { name: "Thovayal",                     serving: "1 tsp",                tags: ["veg","light"],          protein: 1,  carbs: 2,  fat: 1,  cal: 21  },
      { name: "Pickle",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 1,  fat: 0,  cal: 5   },
      { name: "Banana",                       serving: "1 medium",             tags: ["veg","light"],          protein: 1,  carbs: 23, fat: 0,  cal: 89  },
    ],
    snacks: [
      { name: "Butter Biscuit",               serving: "2 biscuits",           tags: ["veg","light"],          protein: 2,  carbs: 14, fat: 5,  cal: 110 },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
    ],
    dinner: [
      { name: "Rajma Curry",                  serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 9,  carbs: 25, fat: 3,  cal: 163 },
      { name: "Chapati",                      serving: "2 chapatis",           tags: ["veg","bread"],          protein: 6,  carbs: 30, fat: 2,  cal: 162 },
      { name: "Dal Tadka",                    serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 10, carbs: 22, fat: 4,  cal: 165 },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Carrot Poriyal",               serving: "1 katori (~80g)",      tags: ["veg","light"],          protein: 1,  carbs: 8,  fat: 2,  cal: 56  },
      { name: "Rasam",                        serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 1,  carbs: 5,  fat: 0,  cal: 25  },
      { name: "Curd",                         serving: "1 katori (100g)",      tags: ["veg","protein"],        protein: 3,  carbs: 4,  fat: 2,  cal: 46  },
      { name: "Pickle",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 1,  fat: 0,  cal: 5   },
      { name: "Salad (Cucumber + Carrot)",    serving: "1 katori (~100g)",     tags: ["veg","light"],          protein: 1,  carbs: 6,  fat: 0,  cal: 28  },
      { name: "Rose Milkshake (veg only)",    serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 4,  carbs: 20, fat: 3,  cal: 123 },
    ],
  },

  saturday: {
    breakfast: [
      { name: "Rawa Idli",                    serving: "3 idlis",              tags: ["veg","light"],          protein: 6,  carbs: 30, fat: 4,  cal: 180 },
      { name: "Rawa Chutney",                 serving: "2 tbsp",               tags: ["veg","light"],          protein: 1,  carbs: 4,  fat: 3,  cal: 47  },
      { name: "Sambar",                       serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 4,  carbs: 10, fat: 1,  cal: 65  },
      { name: "Potato Onion Poha",            serving: "1 plate (~200g)",      tags: ["veg","light"],          protein: 5,  carbs: 35, fat: 5,  cal: 205 },
      { name: "Wheat Bread",                  serving: "2 slices",             tags: ["veg","bread"],          protein: 4,  carbs: 26, fat: 2,  cal: 140 },
      { name: "Butter",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 4,  cal: 36  },
      { name: "Jam",                          serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 6,  fat: 0,  cal: 25  },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
      { name: "Boiled Egg",                   serving: "1 egg",                tags: ["nonveg","protein"],     protein: 6,  carbs: 0,  fat: 5,  cal: 70  },
    ],
    lunch: [
      { name: "Chapati",                      serving: "2 rotis",              tags: ["veg","bread"],          protein: 6,  carbs: 30, fat: 2,  cal: 162 },
      { name: "Vegetable Kadhai",             serving: "1 katori (~150g)",     tags: ["veg","light"],          protein: 4,  carbs: 18, fat: 5,  cal: 133 },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Vathakuzhambu",                serving: "1 ladle (100ml)",      tags: ["veg","rice"],           protein: 2,  carbs: 12, fat: 2,  cal: 74  },
      { name: "Milagu Rasam",                 serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 1,  carbs: 5,  fat: 1,  cal: 33  },
      { name: "Curd",                         serving: "1 katori (100g)",      tags: ["veg","protein"],        protein: 3,  carbs: 4,  fat: 2,  cal: 46  },
      { name: "Keerai Porial",                serving: "1 katori (~80g)",      tags: ["veg","light"],          protein: 3,  carbs: 6,  fat: 2,  cal: 54  },
      { name: "Paruppu Podi",                 serving: "1 tsp",                tags: ["veg","light"],          protein: 2,  carbs: 4,  fat: 1,  cal: 33  },
      { name: "Gingelly Oil",                 serving: "½ tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 2,  cal: 18  },
      { name: "Thovayal",                     serving: "1 tsp",                tags: ["veg","light"],          protein: 1,  carbs: 2,  fat: 1,  cal: 21  },
      { name: "Fryams",                       serving: "5–6 pieces",           tags: ["veg","light"],          protein: 1,  carbs: 6,  fat: 2,  cal: 45  },
      { name: "Pickle",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 1,  fat: 0,  cal: 5   },
      { name: "Papaya",                       serving: "1 cup (~150g)",        tags: ["veg","light"],          protein: 1,  carbs: 14, fat: 0,  cal: 60  },
      { name: "Lemon Mint Juice",             serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 0,  carbs: 8,  fat: 0,  cal: 32  },
    ],
    snacks: [
      { name: "Pani Puri",                    serving: "6 pieces",             tags: ["veg","light"],          protein: 3,  carbs: 20, fat: 4,  cal: 128 },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
    ],
    dinner: [
      { name: "Phulka",                       serving: "3 phulkas",            tags: ["veg","bread"],          protein: 6,  carbs: 30, fat: 2,  cal: 162 },
      { name: "Cabbage Green Peas Masala",    serving: "1 katori (~120g)",     tags: ["veg","light"],          protein: 4,  carbs: 14, fat: 4,  cal: 108 },
      { name: "Kadai Paneer",                 serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 12, carbs: 10, fat: 10, cal: 178 },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Kadhi Pakoda Curry",           serving: "1 katori (~150g)",     tags: ["veg","light"],          protein: 5,  carbs: 18, fat: 5,  cal: 137 },
      { name: "Rasam",                        serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 1,  carbs: 5,  fat: 0,  cal: 25  },
      { name: "Curd",                         serving: "1 katori (100g)",      tags: ["veg","protein"],        protein: 3,  carbs: 4,  fat: 2,  cal: 46  },
      { name: "Pickle",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 1,  fat: 0,  cal: 5   },
      { name: "Salad (Cucumber + Carrot)",    serving: "1 katori (~100g)",     tags: ["veg","light"],          protein: 1,  carbs: 6,  fat: 0,  cal: 28  },
      { name: "Millet Buttermilk",            serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 3,  carbs: 6,  fat: 2,  cal: 54  },
    ],
  },

  sunday: {
    breakfast: [
      { name: "Pav Bhaji",                    serving: "2 pav + 1 katori bhaji",tags:["veg","bread"],         protein: 8,  carbs: 48, fat: 10, cal: 315 },
      { name: "Millet Pongal",                serving: "1 plate (~250g)",      tags: ["veg","light"],          protein: 6,  carbs: 36, fat: 3,  cal: 195 },
      { name: "Sambar",                       serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 4,  carbs: 10, fat: 1,  cal: 65  },
      { name: "Coconut Chutney",              serving: "2 tbsp",               tags: ["veg","light"],          protein: 1,  carbs: 4,  fat: 4,  cal: 55  },
      { name: "Bread",                        serving: "2 slices",             tags: ["veg","bread"],          protein: 4,  carbs: 26, fat: 2,  cal: 140 },
      { name: "Butter",                       serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 0,  fat: 4,  cal: 36  },
      { name: "Jam",                          serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 6,  fat: 0,  cal: 25  },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
      { name: "Egg Bhurji",                   serving: "2 eggs scrambled",     tags: ["nonveg","protein"],     protein: 10, carbs: 2,  fat: 8,  cal: 120 },
    ],
    lunch: [
      { name: "Dum Paneer Biryani",           serving: "1 plate (~350g)",      tags: ["veg","protein","rice"], protein: 18, carbs: 62, fat: 12, cal: 435, exclusiveGroup: "sun-lunch-biryani" },
      { name: "Dum Chicken Biryani",          serving: "1 plate (~350g)",      tags: ["nonveg","protein","rice"],protein:25, carbs: 58, fat: 13, cal: 453, exclusiveGroup: "sun-lunch-biryani" },
      { name: "Gobi Aloo Masala",             serving: "1 katori (~120g)",     tags: ["veg","light"],          protein: 3,  carbs: 16, fat: 4,  cal: 112 },
      { name: "Onion Raita",                  serving: "1 katori (100g)",      tags: ["veg","protein"],        protein: 3,  carbs: 5,  fat: 1,  cal: 42  },
      { name: "Brinjal Gravy",                serving: "1 katori (~120g)",     tags: ["veg","light"],          protein: 2,  carbs: 10, fat: 3,  cal: 75  },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Mysore Rasam",                 serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 1,  carbs: 6,  fat: 1,  cal: 37  },
      { name: "Curd",                         serving: "1 katori (100g)",      tags: ["veg","protein"],        protein: 3,  carbs: 4,  fat: 2,  cal: 46  },
      { name: "Rice Pickle",                  serving: "1 tsp",                tags: ["veg","light"],          protein: 0,  carbs: 1,  fat: 0,  cal: 5   },
      { name: "Mixed Fruits",                 serving: "1 cup (~150g)",        tags: ["veg","light"],          protein: 1,  carbs: 18, fat: 0,  cal: 72  },
      { name: "Lemon Mint Juice",             serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 0,  carbs: 8,  fat: 0,  cal: 32  },
      { name: "Chilled Badam Milk",           serving: "1 glass (200ml)",      tags: ["nonveg","protein"],     protein: 6,  carbs: 20, fat: 5,  cal: 150 },
    ],
    snacks: [
      { name: "Boiled Chana Chat",            serving: "1 cup (~150g)",        tags: ["veg","protein"],        protein: 8,  carbs: 24, fat: 2,  cal: 148 },
      { name: "Tea / Coffee / Milk",          serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 2,  carbs: 6,  fat: 2,  cal: 50  },
    ],
    dinner: [
      { name: "Mixed Vegetable Porial",       serving: "1 katori (~100g)",     tags: ["veg","light"],          protein: 3,  carbs: 12, fat: 2,  cal: 78  },
      { name: "Idli",                         serving: "3 idlis",              tags: ["veg","light"],          protein: 5,  carbs: 30, fat: 1,  cal: 150 },
      { name: "Coconut Chutney",              serving: "2 tbsp",               tags: ["veg","light"],          protein: 1,  carbs: 4,  fat: 4,  cal: 55  },
      { name: "Sambar",                       serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 4,  carbs: 10, fat: 1,  cal: 65  },
      { name: "White Rice",                   serving: "1 plate (~200g)",      tags: ["veg","rice"],           protein: 4,  carbs: 45, fat: 1,  cal: 206 },
      { name: "Dal Makhani",                  serving: "1 katori (~150g)",     tags: ["veg","protein"],        protein: 10, carbs: 20, fat: 5,  cal: 165 },
      { name: "Rasam",                        serving: "1 cup (200ml)",        tags: ["veg","light"],          protein: 1,  carbs: 5,  fat: 0,  cal: 25  },
      { name: "Salad (Cucumber + Carrot + Cabbage)", serving: "1 katori (~100g)", tags: ["veg","light"],      protein: 1,  carbs: 7,  fat: 0,  cal: 32  },
      { name: "Milk",                         serving: "1 glass (250ml)",      tags: ["veg","protein"],        protein: 8,  carbs: 12, fat: 5,  cal: 125 },
      { name: "Buttermilk",                   serving: "1 glass (200ml)",      tags: ["veg","light"],          protein: 3,  carbs: 4,  fat: 2,  cal: 45  },
    ],
  },
};
